### PR TITLE
fix(categories): better web results rankings

### PR DESCRIPTION
**Pull request by aleksasiriski**
@matijakljajic @k4lizen Do you agree with this?

### CODE REVIEW

**Comment by aleksasiriski** [comment]
Btw you can use the Netlify preview deployment above to test the changes, since the agent now works as the frontend tells it to :)

**Comment by matijakljajic** [comment]
Can you give some example queries you've seen where this config works better?

**Comment by aleksasiriski** [comment]
Not so much in query but in a scenario:

I noticed ocni that only google, mojeek and bieg returned results and there were many unique ones which ended up having the top 5 results be all from different engines and since all engines had the same multiplier it resulted in a random order (mojeek result was first). This made me come up with tdis slight change of ranking, preferring results from Google and Bing and all of their leeches :)

**Comment by aleksasiriski** [comment]
@matijakljajic What's the conclusion here?

**Review by k4lizen — APPROVED** [review]

**Pull request merged**
